# Generated by Django 3.2 on 2022-06-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='courseteachers',
            options={'verbose_name': 'Курс с учителем', 'verbose_name_plural': 'Курсы с учителями'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('course', 'num'), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
